### ISSUE TITLE
Save Error: trying to save NES Roms .rdb file

### ISSUE THREAD

**Issue by toughguystudios** [schellingb/RDBEd#4]
Hello,
  I'm trying to update the NES rom rdb file as per the instruction that was provided in this previous issue:

https://github.com/libretro/RetroArch/issues/11275

I followed the instructions laid out and went to Tools - merge data, merge with the name field, and went to validate, and validated under CRC, clicked the errors at the bottom, then removed all fields that were red.
   But Regardless, ANYTHING I try to save, I keep getting a save error. After following the steps provided. I received the following error message:

System.MissingMethodException: Method not found: 'VoidSystem.IO.BinaryWriter..ctor(System.IO.Stream, System. Text.Encoding, Boolean)'
   at RDBDd.EntryList.SaveRDB(String path)
   at RDBEd.RDBEdUI.Save(String saveFile, Boolean keepLoaded, Boolean forceRDB, Boolean forceDAT)

Can you explain what this means and how to fix it?

**Comment by schellingb** [comment]
What if you just open an RDB and directly go to File -> Save As and try to save into a new RDB file? The error seems fairly generic and it sounds unrelated to any changes you made between open and saving so I'd like to confirm that first.

**Comment by toughguystudios** [comment]
I agree, I tried that as well, just saving as a new file. And I tried export rdb file as well. I get the same style of error message.
    Now mind you, I was able to successfully do this a week ago. I went through your directions, saved the file, it had no problem. I don’t know why as of recent it’s giving me this error message...
